name: Assembly ini files
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Make
        run: make
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Build dist files
